# Generated by Django 5.0 on 2023-12-18 06:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('mainapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Dataset',
            fields=[
                ('Data_id', models.AutoField(primary_key=True, serialize=False)),
                ('Image', models.ImageField(upload_to='media/')),
            ],
            options={
                'db_table': 'upload',
            },
        ),
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('Feed_id', models.AutoField(primary_key=True, serialize=False)),
                ('Rating', models.CharField(max_length=100, null=True)),
                ('Review', models.CharField(max_length=225, null=True)),
                ('Sentiment', models.CharField(max_length=100, null=True)),
                ('datetime', models.DateTimeField(auto_now=True)),
                ('Reviewer', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='mainapp.user')),
            ],
            options={
                'db_table': 'feedback_details',
            },
        ),
    ]
